# 这是一个示例配置文件，你可以根据自己的需求进行修改保存为config.yml
servers:
  - name: "server1" # 服务器名称，对应GroupID，v11下为数字，v12下为字符串
    address: "mc.example.top" # 服务器地址
    reconnect_interval: 5  # 重连间隔，单位秒，0为不重连，建议大一点不然被反作弊封号
    auth: "auth_example_online"  # 服务器的认证信息

  - name: "Server2"
    address: "server.top"
    reconnect_interval: 5
    auth: "auth_example_offline"

auth: # 自定义认证信息
  auth_example_online: # 服务器的认证信息
    online: true  # 在线模式下使用交互式登录
    name:   # 在线模式下不生效
    uuid:   # 在线模式下不生效
  auth_example_offline:
    online: false
    name: "Bot"
    uuid: "00000000-0000-0000-0000-000000000000"

onebot:
  reverse_ws:
    - address: "ws://127.0.0.1:8080/onebot/v12"
      reconnect_interval: 5  # 重连间隔，单位秒，0为不重连

  bot:
    self_id: 114514  # 机器人的ID，v11下需使用数字形式，v12下使用字符串形式，要兼容的话请使用字符串数字形式
    player_id_type: "uuid_int"  # 为兼容onebotv11，用户的ID传输模式，uuid_int为UUID的整数形式(在某些语言下可能无法处理较大的整数，例如Javascript)，primary_key为使用数据库自增主键作为id