Servers:
  # 一个服务器是一个群，ServerName对应GroupID
  - Name: "Server1"
    Address: "mc.example.top"
    Online: true  # 正版模式使用交互式登录微软账户
    ReconnectInterval: 5  # 重连间隔，单位秒，0为不重连


  - Name: "Server2"
    Address: "server.top"
    Online: false
    ReconnectInterval: 5
    BotPlayer:
      Name: "Bot"
      UUID: # Bot的UUID，留空则随机生成


OneBotConnection:
# 连接 OneBot 的配置
  - ReverseWS:
      Address: "ws://127.0.0.1:8080/onebot/v12"
      ReconnectInterval: 5  # 重连间隔，单位秒，0为不重连